import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.css"
import ReduxStateProvider from "./components/ReduxStateProvider"

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
  variable: "--font-roboto",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans`}>
        <ReduxStateProvider>{children}</ReduxStateProvider>
      </body>
    </html>
  )
}
